### ISSUE TITLE
Visualization for MIBI

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-visualization#13]
- [ ] Learn what the file structure is
- [ ] Add vitessce-hints: https://github.com/hubmapconsortium/search-api/issues/405
- [ ] ...?

**Comment by mccalluc** [comment]
@pdblood 

> Ingestion of the MIBI data is awaiting some pipeline work from 
> [@Matt Ruffalo](https://hubmapconsortium.slack.com/team/UKGFW2RTN)
>  ‘s group that 
> [@Vasyl Vaskivskyi](https://hubmapconsortium.slack.com/team/UV46VHB0Q)
>  is doing.

There doesn't seem to be an ask for any work from us, so I'll close.

**Comment by ilan-gold** [comment]
Just to clarify here for anyone who comes across this, the data structure of the MIBI data should be identical to CODEX since the outputs are the same - segmentation mask pyramid + SPRM + image pyramid.  It shouldn't matter that the underlying assay is different.

**Comment by ilan-gold** [comment]
If this is wrong, please update @pdblood.
