### ISSUE TITLE
What's special about `b'\x01'`?

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-visualization#18]
What does it mean? Is it coming from our pipeline, or is it something more general about zarr?

_from https://github.com/hubmapconsortium/portal-visualization/pull/8#discussion_r808375123_

**Comment by mruffalo** [comment]
Isn't this the one-byte encoding of "true"? If a dataset has been run through Azimuth but not annotated, this value is 0 instead of 1 (for `is_annotated` being `False`):
```
[ruffalo@login000 /hive/hubmap/data/consortium/EXT - Human Cell Atlas/82d0134c99dc400d006f6e0ceb0240f7/hubmap_ui/anndata-zarr/secondary_analysis.zarr]$ hexdump -C uns/annotation_metadata/is_annotated/0 
00000000  00                                                |.|
00000001
```

**Comment by mccalluc** [comment]
Thanks! That helps.
