### ISSUE TITLE
Fix build after Cell dive PR

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-visualization#22]
After PR #3, tests are failing. I think somehow the new tests that were added while that PR was out are conflicting... but the merge from main should have caught that? Anyway, just needs to be fixed.

When I checkout the last commit in that branch, 9687ea5, tests fail for me?! `15 failed, 4 passed`

**Comment by ilan-gold** [comment]
Sorry about this @mccalluc!  It also seemed like things were working so not sure what happened here...

**Comment by mccalluc** [comment]
Fixed by #23
